<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CSharpFunctionalExtensions" Version="3.6.0" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="DependencyPropertyGenerator" Version="1.5.0" />
    <PackageVersion Include="HtmlAgilityPack" Version="1.12.2" />
    <PackageVersion Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Playwright" Version="1.54.0" />
    <PackageVersion Include="PuppeteerSharp" Version="20.2.2" />
    <PackageVersion Include="Refit" Version="8.0.0" />
    <PackageVersion Include="Refit.HttpClientFactory" Version="8.0.0" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="9.0.2" />
    <PackageVersion Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="Serilog.Sinks.Seq" Version="9.0.0" />
  </ItemGroup>
</Project>