<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AssemblyName>FreelanceJobs</AssemblyName>
		<ApplicationIcon>appicon.ico</ApplicationIcon>
		<RootNamespace>VRT.FreelanceJobs.Wpf</RootNamespace>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<EnableDefaultContentItems>false</EnableDefaultContentItems>
		<UserSecretsId>02d25faf-1a85-43ef-baa7-c34746dd71b1</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="appsettings.json" CopyToPublishDirectory="Never">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</Content>		
	</ItemGroup>


	<ItemGroup>
		<Content Include="appicon.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="CSharpFunctionalExtensions" />
		<PackageReference Include="DependencyPropertyGenerator">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="HtmlAgilityPack" />
		<PackageReference Include="MaterialDesignThemes" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
		<PackageReference Include="Microsoft.Playwright" />
		<PackageReference Include="Refit" />
		<PackageReference Include="Refit.HttpClientFactory" />
		<PackageReference Include="Serilog.Extensions.Logging" />
		<PackageReference Include="Serilog.Settings.Configuration" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="Serilog.Sinks.Seq" />
	</ItemGroup>
</Project>
